# Generated by Django 5.1.4 on 2025-01-07 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_follows_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
