# Generated by Django 5.1.4 on 2025-01-07 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
