# Generated by Django 5.1.4 on 2025-01-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_user_followers_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
