# Generated by Django 5.1.4 on 2025-01-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_follows_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
    ]
